version: "3.4"

services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:latest
    ports:
      - 8123:8123
      - 3218:3218
    depends_on:
      - mqtt
      - postgres
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    volumes:
      - /home/pi/home-assistant-configs:/config
      - /mnt/dehydrated:/mnt/dehydrated
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HTTP_SSL_CERTIFICATE=/mnt/dehydrated/certs/homeassistant/fullchain.pem
      - HTTP_SSL_KEY=/mnt/dehydrated/certs/homeassistant/privkey.pem
      - HTTP_BASE_URL=${HA_HTTP_BASE_URL}
      - TRADFRI_GATEWAY=${HA_TRADFRI_GATEWAY}
    privileged: true
    network_mode: host

  mqtt:
    image: fstehle/rpi-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /mnt/mqtt/config:/mqtt/config:ro
      - /mnt/mqtt/data:/mqtt/data
      - /mnt/mqtt/passwd:/mqtt/passwd
      - /mnt/dehydrated/certs:/mqtt/conf/certs
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    network_mode: host
    privileged: true

  appdaemon:
    image: dmeenhuis/rpi-appdaemon:latest
    volumes:
      - /mnt/appdaemon:/conf
      - /mnt/dehydrated/certs/homeassistant/fullchain.pem:/var/certs/fullchain.pem:ro
      - /mnt/dehydrated/certs/homeassistant/privkey.pem:/var/certs/privkey.pem:ro
    ports:
      - 5050:5050
      - 5000:5000
    privileged: true
    network_mode: host
    depends_on:
      - homeassistant

  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - /mnt/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: host
    privileged: true
